Updated copyright to year 2014

diff --git a/src/main/resources/bin/appCreator b/src/main/resources/bin/appCreator
--- a/src/main/resources/bin/appCreator
+++ b/src/main/resources/bin/appCreator
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (C) 2010-2013 by PhonyTive LLC (http://phonytive.com)
+# Copyright (C) 2010-2014 by PhonyTive LLC (http://phonytive.com)
 # http://astivetoolkit.org
 #
 # This file is part of Astive Toolkit(ATK)
@@ -22,6 +22,8 @@
 # appCreator com.mycompany myproject
 
 # a usage function to display help for the user
+
+command -v mvn >/dev/null 2>&1 || { echo "I require Maven but it's not installed. Aborting." >&2; exit 1; }
 
 usage () {
      echo "appCreator"
diff --git a/src/main/resources/bin/astived b/src/main/resources/bin/astived
--- a/src/main/resources/bin/astived
+++ b/src/main/resources/bin/astived
@@ -19,6 +19,8 @@
 
 # Operations include: Start or stop Astive, deploy or undeploy apps.
 
+command -v java >/dev/null 2>&1 || { echo "I require Java but it's not installed. Aborting." >&2; exit 1; }
+
 # Might fail if $0 is a link
 export ASTIVE_HOME=`dirname "$0"`/..
 export ASTIVE_APPS="$ASTIVE_HOME/apps"
